[package]
name = "hansing-chess"
version = "0.1.0"
authors = ["morri <hansing@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
